"""
LADOCK License Manager (core/license_manager.py)

Offline license system — license keys are generated by the owner
and sent to users via email after verification.

License types:
  ACADEMIC_FREE     — free for everyone (non-commercial) until 2030-12-31; no key needed
  ACADEMIC_DISCOUNT — discounted institutional license, post-2030
  COMMERCIAL        — paid, for-profit use

Key format:
  LADOCK-<BASE64_PAYLOAD>.<HMAC_SIGNATURE>

Payload (JSON):
  {
    "type":    "ACADEMIC_FREE" | "ACADEMIC_DISCOUNT" | "COMMERCIAL",
    "name":    "Recipient name or institution",
    "email":   "user@university.ac.id",
    "issued":  "YYYY-MM-DD",
    "expires": "YYYY-MM-DD" | null   (null = perpetual commercial)
  }
"""

import json
import hmac
import hashlib
import base64
import os
from datetime import date, datetime
from pathlib import Path
from enum import Enum

# ── Secret key (embedded, offline validation) ────────────────────────────────
# Keep this consistent across all LADOCK releases.
_SECRET = b"LADOCK-La-Ode-Aman-2024-UNG-acId-$3cur3"

# ── License storage path ─────────────────────────────────────────────────────
_LICENSE_DIR  = Path.home() / ".ladock"
_LICENSE_FILE = _LICENSE_DIR / "license.key"

# ── Academic free period ─────────────────────────────────────────────────────
ACADEMIC_FREE_UNTIL = date(2030, 12, 31)


class LicenseType(str, Enum):
    ACADEMIC_FREE     = "ACADEMIC_FREE"
    ACADEMIC_DISCOUNT = "ACADEMIC_DISCOUNT"
    COMMERCIAL        = "COMMERCIAL"
    UNLICENSED        = "UNLICENSED"


class LicenseStatus(str, Enum):
    VALID   = "VALID"
    EXPIRED = "EXPIRED"
    INVALID = "INVALID"
    MISSING = "MISSING"


class LicenseInfo:
    def __init__(self, *, type: LicenseType, status: LicenseStatus,
                 name: str = "", email: str = "",
                 issued: str = "", expires: str | None = None,
                 message: str = ""):
        self.type    = type
        self.status  = status
        self.name    = name
        self.email   = email
        self.issued  = issued
        self.expires = expires
        self.message = message

    @property
    def is_valid(self) -> bool:
        return self.status == LicenseStatus.VALID

    @property
    def expires_date(self) -> date | None:
        if self.expires:
            return date.fromisoformat(self.expires)
        return None

    @property
    def days_remaining(self) -> int | None:
        d = self.expires_date
        if d is None:
            return None
        return (d - date.today()).days

    def type_label(self) -> str:
        labels = {
            LicenseType.ACADEMIC_FREE:     "Academic Free",
            LicenseType.ACADEMIC_DISCOUNT: "Academic Discount",
            LicenseType.COMMERCIAL:        "Commercial",
            LicenseType.UNLICENSED:        "Unlicensed",
        }
        return labels.get(self.type, self.type)


# ── Core functions ────────────────────────────────────────────────────────────

def _sign(payload_b64: str) -> str:
    sig = hmac.new(_SECRET, payload_b64.encode(), hashlib.sha256).hexdigest()
    return sig[:32]  # 32 hex chars — compact but sufficient


def generate_key(license_type: str, name: str, email: str,
                 expires: str | None = None) -> str:
    """
    Generate a license key. Called by the owner tool (tools/generate_license.py).
    expires: "YYYY-MM-DD" or None (perpetual, for commercial)
    """
    payload = {
        "type":    license_type,
        "name":    name,
        "email":   email,
        "issued":  date.today().isoformat(),
        "expires": expires,
    }
    payload_json  = json.dumps(payload, separators=(",", ":"))
    payload_b64   = base64.urlsafe_b64encode(payload_json.encode()).decode()
    signature     = _sign(payload_b64)
    return f"LADOCK-{payload_b64}.{signature}"


def validate_key(key: str) -> LicenseInfo:
    """Parse and validate a license key string."""
    try:
        if not key.startswith("LADOCK-"):
            return LicenseInfo(type=LicenseType.UNLICENSED,
                               status=LicenseStatus.INVALID,
                               message="Invalid key format.")
        inner = key[len("LADOCK-"):]
        if "." not in inner:
            raise ValueError
        payload_b64, sig = inner.rsplit(".", 1)

        # Verify signature
        expected = _sign(payload_b64)
        if not hmac.compare_digest(sig, expected):
            return LicenseInfo(type=LicenseType.UNLICENSED,
                               status=LicenseStatus.INVALID,
                               message="License key is invalid or has been tampered with.")

        # Decode payload
        payload = json.loads(base64.urlsafe_b64decode(payload_b64).decode())
        ltype   = LicenseType(payload["type"])
        expires = payload.get("expires")

        # Check expiry
        if expires:
            exp_date = date.fromisoformat(expires)
            if date.today() > exp_date:
                return LicenseInfo(
                    type=ltype, status=LicenseStatus.EXPIRED,
                    name=payload.get("name", ""),
                    email=payload.get("email", ""),
                    issued=payload.get("issued", ""),
                    expires=expires,
                    message=f"License expired on {expires}.",
                )

        return LicenseInfo(
            type=ltype, status=LicenseStatus.VALID,
            name=payload.get("name", ""),
            email=payload.get("email", ""),
            issued=payload.get("issued", ""),
            expires=expires,
            message="License is valid.",
        )
    except Exception:
        return LicenseInfo(type=LicenseType.UNLICENSED,
                           status=LicenseStatus.INVALID,
                           message="Could not parse license key.")


# ── Persistence ───────────────────────────────────────────────────────────────

def save_license(key: str) -> None:
    _LICENSE_DIR.mkdir(parents=True, exist_ok=True)
    _LICENSE_FILE.write_text(key.strip(), encoding="utf-8")


def load_license() -> LicenseInfo:
    """Load and validate the stored license. Returns MISSING if none found."""
    if not _LICENSE_FILE.exists():
        # Check if still within academic free period (no key needed)
        if date.today() <= ACADEMIC_FREE_UNTIL:
            return LicenseInfo(
                type=LicenseType.ACADEMIC_FREE,
                status=LicenseStatus.VALID,
                expires=ACADEMIC_FREE_UNTIL.isoformat(),
                message="Academic free period active. No key required until 2030-12-31.",
            )
        return LicenseInfo(
            type=LicenseType.UNLICENSED,
            status=LicenseStatus.MISSING,
            message="No license key found. Please activate LADOCK.",
        )

    key = _LICENSE_FILE.read_text(encoding="utf-8").strip()
    return validate_key(key)


def remove_license() -> None:
    if _LICENSE_FILE.exists():
        _LICENSE_FILE.unlink()


def get_current_license() -> LicenseInfo:
    return load_license()
